In [1]:
import numpy as np

# NumPy Arrays

In [2]:
mylist = [1,2,3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
mylist

[1, 2, 3]

In [5]:
myarray = np.array(mylist)

In [6]:
myarray

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix) # O NumPy transforma a lista em um objeto bidimensional com 3 linhas e 3 colunas

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,101,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [18]:
np.zeros((3,5)) # (linhas, colunas)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones(10) # Mesmo funcionamento do zeros

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [88]:
np.linspace(0,10,5) # (ponto de partida, ultimo número, quantidade de intervalos)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [36]:
np.random.rand(5,3) # Amostra aleatória com distribuição uniforme
                    #(todos os números com a mesma probabilidade de entrarem na amostra) entre 0 e 0,9999999

array([[0.90965765, 0.52198057, 0.86282393],
       [0.16883213, 0.59232763, 0.43334305],
       [0.02756713, 0.38222565, 0.45621135],
       [0.89048242, 0.6765974 , 0.31797364],
       [0.46100122, 0.04789857, 0.85359028]])

In [39]:
np.random.randn(2,3) # Amostra aleatória com distribuição normal padrão começando em 0 com variância de 1
                     # valores mais próximos de 0 têm maior probabilidade de aparecerem

array([[ 0.60622884,  1.51175485, -0.62714079],
       [-0.64022453, -0.07495512, -1.12062321]])

In [42]:
np.random.randint(0,101,(5,4)) # Amostra aleatória de inteiros com distribuição uniforme

array([[ 8, 67, 21, 84],
       [30, 68, 32, 90],
       [60, 84, 93, 38],
       [69, 44, 78, 72],
       [65, 82, 46, 53]])

In [45]:
np.random.seed(101)
np.random.rand(4) # O seed deve estar na mesma celula que se deseja aplicá-lo

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [46]:
arr = np.arange(0,25)

In [48]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
arr.reshape(4,5) # Calculando linhas por colunas o resultado deve ser igual a quantidade de elementos

ValueError: cannot reshape array of size 25 into shape (4,5)

In [56]:
ranarr = np.random.randint(0,101,10)

In [57]:
ranarr

array([ 9, 77, 40,  4, 63, 40, 60, 92, 64,  5])

In [59]:
ranarr.max()

92

In [60]:
ranarr.min()

4

In [62]:
ranarr.argmax() # Fornece o index do máximo

7

In [63]:
ranarr.argmin()

3

In [64]:
ranarr.dtype

dtype('int32')

In [72]:
array = np.arange(0,32,1)

In [73]:
array.shape

(32,)

In [75]:
array = array.reshape(8,4)

In [76]:
array.shape

(8, 4)

In [77]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [86]:
array.reshape(32, )

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [83]:
array.reshape(1,32)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

# Indexing and Selection

In [89]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
arr[8]

8

In [91]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [92]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
slice_of_arr = arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [94]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [98]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [99]:
arr_copy = arr.copy()

In [100]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [101]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [102]:
arr_2nd = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2nd

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [104]:
arr_2nd[-1, 0]

35

In [105]:
arr_2nd[:2,1:]

array([[10, 15],
       [25, 30]])

In [106]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

# NumPy Operations

In [111]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [113]:
arr - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [114]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [115]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [116]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [117]:
arr / arr

<ipython-input-117-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [119]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [120]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [121]:
np.log(arr)

<ipython-input-121-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [128]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [126]:
arr2d.sum(axis = 0) # apesar do eixo ser as linhas ele soma os valores das colunas

array([50, 55, 60, 65, 70])

In [127]:
arr2d.sum(1)

array([ 10,  35,  60,  85, 110])